repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.253
    hooks:
    - id: ruff
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
    - id: nbqa-black
    - id: nbqa-ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.0'
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: ['--without-urls']